stages:
  - build
  - deploy

services:
  - docker:dind

before_script:
  - export DOCKER_BUILDKIT=1

build:
  image: docker
  stage: build
  script:
    - docker build -o dist .
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public # mandatory, other folder won't work
  only:
    - master # or dev, the branch you want to publish
